- name: config backup of network devices
  hosts: all
  gather_facts: no
  tasks:
  - name: get timestamp
    shell: "date +%Y%m%d-%H-%M-%S"
    register: timestamp

  - name: backup ios config to tftp
    ios_command:
      commands:
        - "copy running-config tftp://192.168.1.15/{{ inventory_hostname }}-running-config-{{ timestamp.stdout }}"
    when: ansible_network_os == 'ios'
