---
- name: config backup of network devices
  hosts: all
  gather_facts: no
  tasks:
  - name: get timestamp
    shell: "date +%Y%m%d-%H-%M-%S"
    register: timestamp

  - name: backup nxos config
    nxos_config:
      backup: yes
      backup_options:
        filename: "running-config-{{ timestamp.stdout }}"
        dir_path: "data/{{ inventory_hostname }}"
    when: ansible_network_os == 'nxos'

  - name: backup junos config
    junos_config:
      backup: yes
      backup_options:
        filename: "running-config-{{ timestamp.stdout }}"
        dir_path: "data/{{ inventory_hostname }}"
    when: ansible_network_os == 'junos'

  - name: backup ios config to tftp
    ios_command:
      commands:
        - "copy running-config tftp://{{ tftp_server }}/{{ inventory_hostname }}-running-config-{{ timestamp.stdout }}"
    when: ansible_network_os == 'ios'
